model:
  NAME: PTSegStacked
  stem_layer: 'kpconv' # 'mlp', 'kpconv', False
  stem_channels: 16 # 1/2, 32->16
  in_channels: 4
  stacked_num: 4
  width: 16 # 1/2, 32->16
  inter_channels: 64 # 1/2, 128->64

batch_size: 4 # width=32, batch_size=2; width=16, batch_size=4
dataloader:
  num_workers: 8 # batch_size=2, num_workers=4; batch_size=4, num_workers=8
  