teacher_model:
  pretrain_path: # pretrained teacher model path
  NAME: PTSegStacked
  stem_layer: 'kpconv' # 'mlp', 'kpconv', False
  stem_channels: 32
  in_channels: 4
  stacked_num: 4
  width: 32
  inter_channels: 128

student_model:
  NAME: PTSegStacked
  stem_layer: 'kpconv' # 'mlp', 'kpconv', False
  stem_channels: 16 # 1/2, 32->16
  in_channels: 4
  stacked_num: 4
  width: 16 # 1/2, 32->16
  inter_channels: 64 # 1/2, 128->64

batch_size: 4
dataloader:
  num_workers: 8
criterion:
  NAME: CrossEntropy
  label_smoothing: 0.2
criterion_kd:
  NAME: CriterionKD
  temperature: 4 
  loss_weight: 0.2
  kd: [2,3] # whether to use kd, [0,3] refer to module 0,3 compute kd loss
  kd_weight: 1.0
  # NOTE: structure [3] is non-stationary, not suggest
  structure: [1,2] # whether to use struction kd, [1,2] refer to module 1,2 compute structure_kd loss
  structure_weight: 1.0
  at: [2,3] # whether to use Attention Transfer, [1,3] refer to module 1,3 compute at loss
  at_weight: 1.0

alpha: [1, 1, 2, 1] # params used for st-kd loss
beta: [1, 1, 1, 1] # params used for at loss
gamma: [1, 1, 1, 2] # params used for kd loss
